data_dir: "/mmfs1/data/liupen/project/dataset/nuclei/worm16/blocks_size512/train/masks_VAE"
image_dir: "/mmfs1/data/liupen/project/dataset/nuclei/worm16/blocks_size512/train/images_VAE"
log_dir: "/mmfs1/data/liupen/project/NucleiVae/expriments/worm16_DE_VAE_with_augmentation_drop08" 
val_dir: "/mmfs1/data/liupen/project/dataset/nuclei/worm16/blocks_size512/val/masks"
val_image_dir: "/mmfs1/data/liupen/project/dataset/nuclei/worm16/blocks_size512/val/images"
target_shape: [64, 96, 96]
ignore_label_zero: True
min_foreground_pixels: 300
batch_size: 16
learning_rate: 0.001
num_epochs: 2000
phase1_epochs: 50
phase2_epochs: 50
latent_dim: 16
base_channel: 16
num_embeddings: 128
max_dropout: 0.8
beta: 1.0
device: "cuda"
